### ISSUE TITLE
Playable Race Health Regen Debuff is not working

### ISSUE THREAD

**Issue by Bazuakh** [theSkyseS/NPCStatRescaler#2]
Hello,

first of all, thanks for your contribution to the modding community,
I did notice a bug in NPC Stats Rescaler Patcher for Synthesis, that I wanted to report. The setting mentioned above has no in game effect. Regardless of setting (0; 0.5 and the default 1), the magnitude of the spell "NPC_stat_rescaler_health_regen_ability "Heath Regen" [SPEL:82001CC5]" is always 100, which it should only be at setting 1. It works fine with the zedit version of the patcher.

Cheers, Moritz

**Comment by theSkyseS** [comment]
[`256ce9`](https://github.com/theSkyseS/NPCStatRescaler/commit/256ce9bff8a16d82848d22c0356949e73ed1c553)

**Comment by theSkyseS** [comment]
Thanks for the report!
